name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Annalyns Infiltration
      run: cd annalyns-infiltration && go test

    - name: Blackjack
      run: cd blackjack && go test

    - name: Booking Up For Beauty
      run: cd booking-up-for-beauty && go test

    - name: Card Tricks 
      run: cd card-tricks && go test

    - name: Cars Assemble
      run: cd cars-assemble && go test

    - name: Hello World
      run: cd hello-world && go test

    - name: Interest Is Interesting
      run: cd interest-is-interesting && go test

    - name: Lasagna
      run: cd lasagna && go test

    - name:  Need For Speed
      run: cd need-for-speed && go test

    - name: Party Robot
      run: cd party-robot && go test

    - name: Vehicle Purchase
      run: cd vehicle-purchase && go test

    - name: Weather Forecast
      run: cd weather-forecast && go test

    - name: Welcome To Tech Palace
      run: cd welcome-to-tech-palace && go test
